---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: sampleproduct-1-services

run:
  path: bash
  args:
    - -exc
    - |
      echo $(pwd)
      cd sampleproduct-1-services
      echo $(pwd)
      chmod 775 mvnw
      ./mvnw clean package
