---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: sampleproduct-1-services
outputs:
  - name: build-output

run:
  path: bash
  args:
    - -exc
    - |
      export TERM=${TERM:-dumb}
      echo $(pwd)
            cd sampleproduct-1-services
            echo $(pwd)
            chmod 755 gradlew
            ./gradlew --no-daemon build
            ls
            ls sampleproduct-1-services/build/libs
            cp sampleproduct-1-services/build/libs/sampleproduct-1-services-1-0.0.1.jar ../build-output
            cp manifest.yml ../build-output

            ls ../build-output
