resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: ((slack.repository))
    tag: ((slack.tag))

resources:
- name: sampleproduct-1-services
  type: git
  source:
    uri: https://github.com/CodeBlueLabs/sampleproduct-1-services.git
    branch: master
    username: OneDigitalAdmin
    password: pass1234

- name: code-analysis
  type: sonar-runner
  source:
    host_url: ((sonar.url))
    login: ((sonar.authtoken))
    project_key: ((sonar.projectkey))

- name: im-notify
  type: slack-notification
  source:
    url: ((slack.url))

- name: deployapp
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: onedigitaladmin@cognizant.com
    password: Pass123$
    organization: Autoloan
    space: PALImmersion
    skip_cert_check: false

jobs:

- name: Unit Test
  serial: true
  plan:
  - get: sampleproduct-1-services
    trigger: true
  - task: unittest
    file: sampleproduct-1-services/ci/test.yml
  - put: code-analysis
    params:
      project_path: codeblue
      project_key: ((sonar.projectkey))
      project_name: ((sonar.projectname))
      project_version: ((project.version))
      sources: ((sonar.sources))
    on_success:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Code Quality Analysis* completed successfully and report published to Sonar
          <http://((domain.name))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Click here> to view the build details
          <((sonar.url))/overview?id=((sonar.projectkey))| Click here> to view the code quality report
    on_failure:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Code Quality Analysis* failed with quality violations, check the code quality report for further details
          <http://((domain.name))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Click here> to view the build details
          <((sonar.url))/overview?id=((sonar.projectkey))| Click here> to view the code quality report
- name: Acceptance Test
  serial: true
  plan:
  - get: sampleproduct-1-services
    passed: ['Unit Test']
    trigger: true
  - task: acceptancetest
    file: sampleproduct-1-services/ci/test.yml
    on_success:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Acceptance Test* completed successfully
          <https://sampleproduct1-ws.cfapps.io/build/spock-reports/index.html| Click here> to view the test report
    on_failure:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Acceptance Test* failed with test case failures, check the build log for details
- name: Build and Deploy
  serial: true
  plan:
  - get: sampleproduct-1-services
    passed: ['Acceptance Test']
    trigger: true
  - task: buildanddeploy
    file: sampleproduct-1-services/ci/build.yml
  - put: deployapp
    params:
      manifest: sampleproduct-1-services/manifest.yml
    on_success:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Build* completed successfully
    on_failure:
      put: im-notify
      params:
        channel: ((slack.channel))
        text: |
          *Build* failed, check the build log for details
